stages:
  - push_to_github

push_to_github:
  stage: push_to_github
  image: alpine:latest
  before_script:
    # 基础设置
    - apk add --no-cache openssh git git-lfs
    
    # SSH 配置
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    # Git 配置
    - git config --global user.email "lijiayang@shoplazza.com"
    - git config --global user.name "Lijiayang"
    
    # Git LFS 配置
    - git lfs install
    - git lfs track "*.pdf" "*.zip"
    - git add .gitattributes
    
    # 提高 Git 缓冲区大小
    - git config --global http.postBuffer 524288000
    - git config --global core.compression 9
    
    # 清理和重置仓库状态
    - git clean -fd
    - git reset --hard HEAD
    - git gc --prune=now
    - git remote prune origin
  script:
    # 确保获取所有 LFS 对象
    - git lfs fetch --all
    - git lfs pull
    
    # 添加并推送到 GitHub
    - git remote add github git@github.com:Shoplazza/help_center_theme.git
    - |
      MAX_RETRIES=3
      RETRY_COUNT=0
      while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
        echo "尝试推送，第 $((RETRY_COUNT + 1)) 次..."
        if git push -f github HEAD:refs/heads/master --verbose; then
          echo "推送成功！"
          break
        fi
        RETRY_COUNT=$((RETRY_COUNT + 1))
        if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
          echo "推送失败，等待 10 秒后重试..."
          sleep 10
          # 在重试之前重新拉取
          git fetch --all
          git reset --hard HEAD
        fi
      done
      if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
        echo "推送失败，达到最大重试次数"
        exit 1
      fi
  only:
    - master  # 仅在 master 分支有代码推送时触发此任务
  variables:
    GIT_LFS_SKIP_SMUDGE: '0'
    GIT_STRATEGY: clone
    GIT_DEPTH: '0'  # 完整克隆仓库